clc;
close all;
clear all;
m = 9;
N = 10;
eta = 1e-2;
Img = prepare_img('./example.jpg');
Img_dct = dct_(Img,N);
[compressed_img,A,B] = compress_img(Img_dct,m,N);
[reconstructed_img] = reconstruct_img(compressed_img,A,B,eta);
[reconstructed_img] = invdct_(reconstructed_img,N);
compare_img(reconstructed_img,Img);
% J1 = imresize(reconstructed_img, [800,NaN], 'nearest');
% figure;
% imshow(J1);
% J2 = imresize(reconstructed_img, [800,NaN], 'bilinear');
% figure;
% imshow(J2);
% J3 = imresize(reconstructed_img, [size(Img,1)*10,NaN], 'bicubic');
% figure;
% imshow(J3);
% title("Enlarged picture");